# Generated by Django 3.2.3 on 2021-05-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20210522_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joballocation',
            name='status',
            field=models.CharField(choices=[('Job allocated', 'Job allocated'), ('Job pending', 'Job pending'), ('Job not allocated', 'Job not allocated')], max_length=200),
        ),
    ]
