# Generated by Django 3.2.3 on 2021-05-22 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_joballocation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.employee'),
        ),
        migrations.AddField(
            model_name='joballocation',
            name='companyname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.hr'),
        ),
        migrations.AddField(
            model_name='joballocation',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.employee'),
        ),
    ]
