# Generated by Django 3.2.3 on 2021-05-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20210522_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr',
            name='jobinstruction',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
