# Generated by Django 3.2.3 on 2021-05-22 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_hr_jobinstruction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobpost', models.CharField(max_length=200, null=True)),
                ('companyname', models.CharField(max_length=200, null=True)),
                ('jobinstruction', models.CharField(max_length=200, null=True)),
                ('jobsample', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hr',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='hr',
            name='jobinstruction',
        ),
        migrations.RemoveField(
            model_name='hr',
            name='jobsample',
        ),
        migrations.AlterField(
            model_name='hr',
            name='companyname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.jobs'),
        ),
    ]
