# Generated by Django 3.2.3 on 2021-05-22 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20210522_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hr',
            old_name='companyname',
            new_name='company',
        ),
    ]
