# Generated by Django 3.2.3 on 2021-05-22 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_rename_companyname_hr_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hr',
            name='company',
        ),
        migrations.AddField(
            model_name='hr',
            name='companyname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='companyname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.hr'),
        ),
    ]
