# Generated by Django 3.2.3 on 2021-05-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_joballocation_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='status',
            field=models.CharField(choices=[('Job allocated', 'Job allocated'), ('Job pending', 'Job pending'), ('Job not allocated', 'Job not allocated')], default='Job not allocated', max_length=200),
        ),
        migrations.DeleteModel(
            name='joballocation',
        ),
    ]
