# Generated by Django 3.2.3 on 2021-05-23 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20210522_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='companyname',
            new_name='status',
        ),
    ]
