# Generated by Django 3.2.3 on 2021-05-23 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_rename_companyname_jobs_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='status',
            new_name='companyname',
        ),
    ]
